name: Build And Deploy

on:
  workflow_call:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Google Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west6-docker.pkg.dev/cas-fee-advanced-mumble
          username: _json_key
          password: ${{ secrets.TF_DEPLOYER_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            europe-west6-docker.pkg.dev/cas-fee-advanced-mumble/mumble/image:latest
            europe-west6-docker.pkg.dev/cas-fee-advanced-mumble/mumble/image:${{ github.sha }}
          secrets: |
            "npmrc=${{ secrets.NPM_RC }}"
  deploy:
    name: Deploy To GCP
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.TF_DEPLOYER_KEY }}'

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve
        env:
          TF_VAR_commit_hash: ${{ github.sha }}
        working-directory: terraform
