name: Release and Deploy via Terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.TF_DEPLOYER_KEY }}'
      - name: Build the Docker image
        run: docker build -t europe-west6-docker.pkg.dev/cas-fee-advanced-mumble/mumble/image . --secret id=npm,src=.npmrc --platform linux/amd64
      - name: Push the Docker image
        run: docker push europe-west6-docker.pkg.dev/cas-fee-advanced-mumble/mumble/image
  deploy:
    name: Deploy Mumble on Google Cloud Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.TF_DEPLOYER_KEY }}'

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve
        working-directory: terraform
