name: Release and Deploy via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Mumble on Google Cloud Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.TF_DEPLOYER_KEY }}'

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve
        working-directory: terraform
